version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true

  install-tools:
    desc: "Установка необходимых утилит локально (опционально)"
    cmds:
      - echo "Installing dependencies..."

  terraform-init:
    desc: "Инициализация Terraform"
    dir: terraform
    cmds:
      - terraform init

  terraform-plan:
    desc: "Планирование инфраструктуры"
    dir: terraform
    cmds:
      - terraform plan

  terraform-apply:
    desc: "Развертывание инфраструктуры в GCP"
    dir: terraform
    cmds:
      - terraform apply

  ansible-ping:
    desc: "Проверка доступности серверов через Ansible"
    dir: ansible
    cmds:
      - ansible all -m ping -i inventory.yml

  deploy:
    desc: "Полный цикл деплоя (Terraform + Ansible)"
    cmds:
      - task: terraform-apply
      - task: ansible-ping

  "k8s:fetch-kubeconfig":
    desc: "Скачивание kubeconfig с мастер-ноды и настройка локального доступа"
    cmds:
      - ansible "136.112.15.165," -i "136.112.15.165," -u ubuntu -m fetch -a "src=/etc/rancher/k3s/k3s.yaml dest=./kubeconfig flat=yes" --become
      - sed -i 's/127.0.0.1/136.112.15.165/g' ./kubeconfig
      - chmod 600 ./kubeconfig
      - echo "Kubeconfig успешно сохранен в ./kubeconfig"
      - echo "Для использования в текущей сессии терминала выполните:"
      - echo "  export KUBECONFIG=\$PWD/kubeconfig"
