all:
  hosts:
    k3s-master-viacheslav:
      ansible_host: 136.112.15.165
      # DO NOT TOUCH - ORACLE CATCHER SERVER
      role: oracle_catcher_only
    k3s-worker-kriolend:
      ansible_host: 34.72.3.83
    k3s-worker-U8197250572:
      ansible_host: 104.154.162.81
  children:
    master:
      hosts:
        k3s-worker-U8197250572:
    'oracle-catcher':
      hosts:
        k3s-master-viacheslav:
    workers:
      hosts:
        k3s-worker-kriolend:
    k3s_cluster:
      children:
        master:
        workers:
